/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package josemancharo.minecraftplugin.listeners;

import org.bukkit.entity.*;
import org.bukkit.event.*;
import org.bukkit.event.entity.*;
import org.bukkit.plugin.java.JavaPlugin;

public final class CreeperListeners extends CustomListener 
{
    public CreeperListeners(JavaPlugin plugin) { super(plugin); }

    @EventHandler
    public void onCreatureSpawn(CreatureSpawnEvent event)
    {
        if (event.getEntityType() == EntityType.CREEPER)
        {
            var entity = (Creeper) event.getEntity();
            entity.setInvisible(true);
        }
    }

    @EventHandler
    public void onTakesDamage(EntityDamageEvent event)
    {
        if (event.getEntityType() == EntityType.CREEPER)
        {
            var entity = (Creeper) event.getEntity();
            entity.setInvisible(false);

            if (entity.getHealth() < 3){
                entity.setPowered(true);
            }
        }
    }
}
